Feature/add wpgraphql
svconectado/website pull request #11
Opened 2020-04-08 06:30 UTC by eduarmreyes

# Antes de enviar el Pull Request
[ ] Confirmo que revisé que mis cambios funcionan
[ ] He adjuntado una imagen de cómo se ven mis cambios (si aplica)
[ ] He ejecutado prettier en los archivos de mis cambios

# Intro
Hace una explicación breve de porqué este PR es importante

# Pruebas
Adjunta imágenes u otro tipo de pruebas para validar los cambios que estás haciendo

2020-04-08 21:26 UTC, cheperecinos93 approved these changes
Agregando WPGraphQL a develop

2020-04-15 05:45 UTC, moudev reviewed
Se necesita hacer merge de `develop` y solucionar conflictos.

2020-04-15 05:46 UTC, eduarmreyes commented
> Se necesita hacer merge de `develop` y solucionar conflictos.

listo

2020-04-15 05:49 UTC, moudev reviewed
Hay que revertir el merge, ya que se están dando prioridad a los cambios procedentes por el PR y dejando de lado a lo hecho en `develop`.

2020-04-15 05:50 UTC, moudev requested changes
Revertir merge `develop`

2020-04-15 05:59 UTC, moudev commented
Noté de los cambios que se hicieron por motivos de prettier. En el siguiente commit se puede notar las modificaciones hechas para que el control de los archivos `.js` y `.jsx` únicamente fueran controlados por `ESlint`, los demás tipos de archivos, totalmente por prettier.

- Commit:  [Add ESlint package](https://github.com/svconectado/website/commit/66497220c1cbb3a0c68aeaeb5b5d4d26805dbfbb)

2020-04-15 16:47 UTC, moudev commented
Para poder pasar con éste pull request es necesario primero de revisar y hacer merge a `develop` del PR #18 . Luego de eso yo procederé a resolver los conflictos debido a que mis modificaciones son un poco grande y entiendo como va todo.

2020-04-17 16:39 UTC, closed without merging