Agregando Footer de pagina y Font-Awesome (Iconos)
svconectado/website pull request #14
Opened 2020-04-09 04:41 UTC by cheperecinos93

# Antes de enviar el Pull Request
[X] Confirmo que revisé que mis cambios funcionan
[X ] He adjuntado una imagen de cómo se ven mis cambios (si aplica)
[X] He ejecutado prettier en los archivos de mis cambios

# Intro
-Se ha realizado el componente footer de pagina web, junto con la respectiva adaptabilidad móvil.
-Se ha agregado Font-Awesome para el uso de los iconos de Redes Sociales, y en adelante cualquier otro tipo de icono se necesite.

# Pruebas
Vista en pantalla de Desktop o Laptop
![footer1](https://user-images.githubusercontent.com/15863634/78858488-d2406d80-79e9-11ea-94e1-636da191e7d9.PNG)
Vista móvil
![footer2](https://user-images.githubusercontent.com/15863634/78858482-ce145000-79e9-11ea-880e-13df1fc30d0a.PNG)

2020-04-09 21:15 UTC, moudev requested changes
Se necesitan correciones para utilizar las clases de TailwindCSS y nomenclatura de ciertos imports.

2020-04-09 22:43 UTC, moudev commented
Luego de actualización de la estructura HTML y de usar más clases de tailwind.

- **Móvil**

![Footer mobile](https://user-images.githubusercontent.com/13499566/78946901-26e2f780-7a81-11ea-8c08-4941d2a55542.png)


- **Desktop**

![Footer Desktop](https://user-images.githubusercontent.com/13499566/78946916-3104f600-7a81-11ea-8bb1-51426bf2a1d8.png)

2020-04-09 23:14 UTC, cheperecinos93 commented
Ya los revise los cambios, perfecto

2020-04-10 04:06 UTC, eduarmreyes approved these changes
se ven bien los cambios, ¿ya está listo para hacer merge?

2020-04-10 04:07 UTC, moudev approved these changes

2020-04-10 04:16 UTC, merged