Update header component to display content from the Wordpress API
svconectado/website pull request #21
Opened 2020-04-16 23:44 UTC by moudev

# Antes de enviar el Pull Request
- [x] Confirmo que revisé que mis cambios funcionan
- [x] He adjuntado una imagen de cómo se ven mis cambios (si aplica)
- [x] He ejecutado prettier en los archivos de mis cambios

# Descripción

- _**PR como propuesta para imitar el funcionamientos del PR #11**_ 

- Actualizando el encabezado con la función de mostrar datos extraídos de la API de Wordpress, estos datos se extraen de una página que necesita tener el nombre _**content-banner-inicio**_ porque la página será buscada por su URL Slug en el componente del encabezado. 

- Fracción de código con la consulta hecha a Wordpress

  ```javascript
      wpgraphql {
          page(id: "content-banner-inicio", idType: URI) {}
      }
  ```

- Si la página no se ha creado, se mostrará un mensaje con las instrucciones. El contenido de _**content-banner-inicio**_ debe ser un bloque HTML personalizado.

- Agregando validaciones en el archivo gatsby-node para crear páginas a partir de datos de la API de Wordpress
- Actualización del archivo .eslintrc con la regla para saltar el error que ocurrió por agregar las validaciones en gatsby-config
- Actualización del componente de encabezado para mostrar datos de la API de Wordpress

# Capturas

- **Mensaje cuando en Wordpress no existe la página "content-banner-inicio"**

![Banner](https://user-images.githubusercontent.com/13499566/79516478-c87dc200-8008-11ea-8f59-eee4df4dcc3a.png)

2020-04-17 01:40 UTC, eduarmreyes requested changes
revisa mi comentario

2020-04-17 01:40 UTC, eduarmreyes commented on src/components/header.js
> +<h1 class="message">
esto lo podés poner en una variable para evitar romper el formato

2020-04-17 16:42 UTC, moudev commented
Se cambió a draft para usar;
- https://www.advancedcustomfields.com/
- https://www.wpgraphql.com/acf/

Para almacenar información dentro de campos especificos, haciendo consulta con graphql para obtenerlos y solo asignarlos como variables dentro del código, por tal motivo hay que revertir los cambios de clases en el header component ya que ahora solo se extraerán variables para ser mostradas.

2020-05-06 01:57 UTC, trejo08 approved these changes

2020-05-06 01:59 UTC, merged